[package]
name = "medialibre"
version = "0.1.0"
authors = ["cerebralcourt <0hhvxhv9@anonaddy.me>"]
edition = "2018"

[dependencies]
actix-web = "3"
handlebars = { version = "3.5", features = ["dir_source"] }
mongodb = "1.1"
serde_json = "1"
